/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.kt.gradle

class App {

}

public class Person{
    private var nome: String = "";
    private var idade: Int = 0;

    fun getNome(): String{
        return this.nome;
    }

    fun getIdade(): Int{
        return this.idade;
    }

    fun setNome(nome: String): Unit{
        this.nome = nome;
    }

    fun setIdade(idade: Int): Unit{
        this.idade = idade;
    }

}

fun main() {
    var pessoa = Person();

    pessoa.setNome("Marcos");
    pessoa.setIdade(35);

    println(pessoa.getNome())
    println(pessoa.getIdade());

}
